# Generated by Django 5.2.15 on 2026-06-14 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_est_outbound_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity_total',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('captured', 'Captured'), ('needs_identification', 'Needs identification'), ('needs_cleaning', 'Needs cleaning'), ('needs_research', 'Needs research'), ('ready_to_list', 'Ready to list'), ('listed', 'Listed'), ('partially_sold', 'Partially sold'), ('sold', 'Sold'), ('stored', 'Stored'), ('archived', 'Archived'), ('in_bulk_lot', 'Part of bulk lot')], default='captured', max_length=30),
        ),
    ]
