# Generated by Django 5.2.15 on 2026-07-05 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_quantity_total_and_more'),
        ('profit', '0002_source_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='disposition',
            field=models.CharField(choices=[('for_sale', 'For sale'), ('scrapped', 'Scrapped')], default='for_sale', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='profit.lot'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='scrapped_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_items', to='profit.source'),
        ),
    ]
