# Generated by Django 5.2.15 on 2026-06-10 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_inventoryitem_est_outbound_shipping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingBoilerplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(default='ebay_au', max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('body_html', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['channel', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ListingDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('exported', 'Exported')], default='draft', max_length=10)),
                ('channel', models.CharField(default='ebay_au', max_length=30)),
                ('channel_data', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=200)),
                ('description_html', models.TextField(blank=True, default='')),
                ('listing_format', models.CharField(choices=[('fixed', 'Fixed price'), ('auction', 'Auction')], default='fixed', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('est_shipping_note', models.CharField(blank=True, default='', max_length=200)),
                ('item_specifics', models.JSONField(blank=True, default=list)),
                ('photo_ids', models.JSONField(blank=True, default=list)),
                ('include_sku_footer', models.BooleanField(default=False)),
                ('title_edited', models.BooleanField(default=False)),
                ('description_edited', models.BooleanField(default=False)),
                ('generated_meta', models.JSONField(blank=True, default=dict)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('boilerplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='listing.listingboilerplate')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_drafts', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item'], name='listing_lis_item_id_8c1843_idx'), models.Index(fields=['status'], name='listing_lis_status_efc7a5_idx')],
            },
        ),
    ]
