# Generated by Django 5.2.15 on 2026-06-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingdraft',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('exported', 'Exported'), ('staged', 'Staged'), ('published', 'Published'), ('publish_failed', 'Publish failed')], default='draft', max_length=20),
        ),
    ]
