# Generated by Django 5.2.15 on 2026-07-05 20:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_disposition_inventoryitem_lot_and_more'),
        ('listing', '0002_alter_listingdraft_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('ebay', 'eBay'), ('facebook_marketplace', 'Facebook Marketplace'), ('gumtree', 'Gumtree'), ('in_person', 'In person'), ('other', 'Other')], default='other', max_length=40)),
                ('listed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('note', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_listings', to='inventory.inventoryitem')),
                ('source_listing_draft', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_listing', to='listing.listingdraft')),
            ],
            options={
                'ordering': ['channel', '-listed_at'],
                'indexes': [models.Index(fields=['item', 'ended_at'], name='chan_list_item_active_idx'), models.Index(fields=['channel', 'ended_at'], name='chan_list_chan_active_idx'), models.Index(fields=['listed_at'], name='channel_listing_listed_idx')],
            },
        ),
    ]
