# Generated by Django 5.2.15 on 2026-06-09 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_inventoryitem_est_outbound_shipping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('links', models.JSONField(blank=True, default=list)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_records', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comparable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('active', 'Active listing'), ('sold', 'Sold / completed'), ('dealer', 'Dealer asking'), ('catalogue', 'Catalogue value'), ('manual_estimate', 'Manual estimate'), ('auction_result', 'Auction result')], max_length=20)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('condition', models.CharField(blank=True, default='', max_length=20)),
                ('url', models.URLField(blank=True, default='')),
                ('observed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparables', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-observed_on', '-created_at'],
                'indexes': [models.Index(fields=['item'], name='research_co_item_id_35e389_idx'), models.Index(fields=['kind'], name='research_co_kind_faa62d_idx')],
            },
        ),
    ]
