# Generated by Django 5.2.15 on 2026-06-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_quantity_total_and_more'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparable',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='comparable',
            name='match_reason',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='comparable',
            name='match_scope',
            field=models.CharField(choices=[('exact', 'Exact item'), ('similar', 'Similar item')], default='similar', max_length=20),
        ),
        migrations.AddField(
            model_name='comparable',
            name='sale_format',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('auction', 'Auction'), ('fixed_price', 'Fixed price'), ('dealer', 'Dealer / guide'), ('other', 'Other')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='comparable',
            name='source_tag',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddIndex(
            model_name='comparable',
            index=models.Index(fields=['source_tag'], name='research_co_source__1a47bd_idx'),
        ),
        migrations.AddIndex(
            model_name='comparable',
            index=models.Index(fields=['sale_format'], name='research_co_sale_fo_e2f48b_idx'),
        ),
        migrations.AddIndex(
            model_name='comparable',
            index=models.Index(fields=['match_scope'], name='research_co_match_s_c5e056_idx'),
        ),
    ]
