# Generated by Django 5.2.15 on 2026-06-11 03:12

import apps.ebay.fields
import apps.ebay.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(default=apps.ebay.models.generate_oauth_state, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(default=apps.ebay.models.oauth_state_expiry)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EbayAccountSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=12)),
                ('business_policies_opted_in', models.BooleanField(null=True)),
                ('payment_policies', models.JSONField(blank=True, default=list)),
                ('fulfillment_policies', models.JSONField(blank=True, default=list)),
                ('return_policies', models.JSONField(blank=True, default=list)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('environment',), name='one_snapshot_per_environment')],
            },
        ),
        migrations.CreateModel(
            name='EbayCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=12)),
                ('ebay_user_id', models.CharField(blank=True, default='', max_length=120)),
                ('ebay_username', models.CharField(blank=True, default='', max_length=120)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('refresh_token', apps.ebay.fields.EncryptedTextField()),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_token', apps.ebay.fields.EncryptedTextField(blank=True, default='')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('last_refresh_error', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebay_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('environment',), name='one_credential_per_environment')],
            },
        ),
    ]
