# Generated by Django 5.2.15 on 2026-06-14 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0002_ebayapptoken_merchantlocation'),
        ('inventory', '0003_inventoryitem_quantity_total_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayOrderSyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=12, unique=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('lookback_days', models.PositiveIntegerField(default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EbayOrderDuplicateCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=12)),
                ('ebay_order_id', models.CharField(max_length=80)),
                ('ebay_line_item_id', models.CharField(max_length=120)),
                ('sku', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_date', models.DateField()),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('linked', 'Linked'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_duplicate_candidates', to='inventory.inventoryitem')),
                ('manual_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_duplicate_candidates', to='sales.salerecord')),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'sale_date'], name='ebay_ebayor_status_649e3d_idx'), models.Index(fields=['sku'], name='ebay_ebayor_sku_24cabf_idx'), models.Index(fields=['item'], name='ebay_ebayor_item_id_f7439e_idx')],
                'constraints': [models.UniqueConstraint(fields=('environment', 'ebay_order_id', 'ebay_line_item_id'), name='uniq_ebay_duplicate_order_line')],
            },
        ),
        migrations.CreateModel(
            name='EbayOrderStaging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=12)),
                ('ebay_order_id', models.CharField(max_length=80)),
                ('ebay_line_item_id', models.CharField(max_length=120)),
                ('sku', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_date', models.DateField()),
                ('actual_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fee_status', models.CharField(choices=[('authoritative', 'Authoritative'), ('estimated_or_unmapped', 'Estimated or unmapped')], default='estimated_or_unmapped', max_length=32)),
                ('buyer_region', models.CharField(blank=True, default='', max_length=80)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('finance_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('resolved_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_sources', to='sales.salerecord')),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'sale_date'], name='ebay_ebayor_status_1d8045_idx'), models.Index(fields=['sku'], name='ebay_ebayor_sku_595919_idx'), models.Index(fields=['ebay_order_id', 'ebay_line_item_id'], name='ebay_ebayor_ebay_or_6e9e53_idx')],
                'constraints': [models.UniqueConstraint(fields=('environment', 'ebay_order_id', 'ebay_line_item_id'), name='uniq_ebay_staging_order_line')],
            },
        ),
    ]
