# Generated by Django 5.2.15 on 2026-06-14 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_inventoryitem_quantity_total_and_more'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=120)),
                ('proposed_value', models.JSONField()),
                ('source', models.CharField(choices=[('ocr', 'OCR'), ('duplicate', 'Duplicate image'), ('later_ai', 'Later AI')], max_length=20)),
                ('confidence_band', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('candidate', 'Candidate')], max_length=20)),
                ('evidence', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('edited', 'Edited'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('resolved_value', models.JSONField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_suggestions', to='inventory.inventoryitem')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_suggestions', to='photos.photoasset')),
            ],
            options={
                'ordering': ['confidence_band', '-created_at'],
                'indexes': [models.Index(fields=['item', 'status'], name='suggestion_item_status_idx'), models.Index(fields=['source', 'status'], name='suggestion_source_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImageFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perceptual_hash', models.CharField(db_index=True, max_length=16)),
                ('algorithm', models.CharField(default='average_hash_8x8', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_fingerprints', to='inventory.inventoryitem')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprint', to='photos.photoasset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item'], name='fingerprint_item_idx'), models.Index(fields=['perceptual_hash'], name='fingerprint_hash_idx')],
            },
        ),
    ]
