# Generated by Django 5.2.15 on 2026-06-15 03:08

import apps.ebay.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        ('inventory', '0003_inventoryitem_quantity_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=40, unique=True)),
                ('model_id', models.CharField(default='gpt-4.1-mini', max_length=120)),
                ('api_key', apps.ebay.fields.EncryptedTextField()),
                ('monthly_budget_cap_usd', models.DecimalField(decimal_places=2, default='5.00', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
        migrations.AlterField(
            model_name='fieldsuggestion',
            name='source',
            field=models.CharField(choices=[('ocr', 'OCR'), ('duplicate', 'Duplicate image'), ('ai', 'AI research'), ('later_ai', 'Later AI')], max_length=20),
        ),
        migrations.CreateModel(
            name='AIResearchCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[('identify', 'Identify and fill'), ('price_assist', 'Price assist')], max_length=24)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], max_length=16)),
                ('provider', models.CharField(max_length=40)),
                ('model_id', models.CharField(max_length=120)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('exif_stripped', models.BooleanField(default=False)),
                ('suggestions_created', models.PositiveIntegerField(default=0)),
                ('search_terms_created', models.PositiveIntegerField(default=0)),
                ('reference_links_created', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default='0.000000', max_digits=10)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('response_metadata', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_research_calls', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReferenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=1000)),
                ('source_basis', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reference_links', to='inventory.inventoryitem')),
                ('created_by_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_links', to='intelligence.airesearchcall')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIResearchSearchTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phrase', models.CharField(max_length=240)),
                ('source_basis', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_terms', to='intelligence.airesearchcall')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_search_terms', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='airesearchcall',
            index=models.Index(fields=['phase', 'created_at'], name='ai_call_phase_created_idx'),
        ),
        migrations.AddIndex(
            model_name='airesearchcall',
            index=models.Index(fields=['provider', 'created_at'], name='ai_call_provider_created_idx'),
        ),
        migrations.AddIndex(
            model_name='aireferencelink',
            index=models.Index(fields=['item', 'created_at'], name='ai_ref_item_created_idx'),
        ),
        migrations.AddIndex(
            model_name='airesearchsearchterm',
            index=models.Index(fields=['item', 'is_active', 'created_at'], name='ai_term_item_active_idx'),
        ),
    ]
