# Generated by Django 5.2.15 on 2026-06-10 03:07

from django.db import migrations


def set_gold_profile_key(apps, schema_editor):
    ProductCategory = apps.get_model("catalog", "ProductCategory")
    ProductCategory.objects.filter(slug="gold").update(profile_key="gold")


def unset_gold_profile_key(apps, schema_editor):
    ProductCategory = apps.get_model("catalog", "ProductCategory")
    ProductCategory.objects.filter(slug="gold", profile_key="gold").update(profile_key="")


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_gold_profile_key, unset_gold_profile_key),
    ]
