EBAY_TITLE_MAX = 80

ALLOWED_HTML_TAGS = {
    "h2",
    "h3",
    "p",
    "ul",
    "ol",
    "li",
    "strong",
    "em",
    "table",
    "tbody",
    "tr",
    "th",
    "td",
    "br",
}

BLOCKED_FIELDS = {
    "imei",
    "serial_no",
    "acquisition_cost",
    "purchase_price",
    "refurb_cost",
    "true_cost",
    "inbound_shipping_cost",
    "est_outbound_shipping",
    "est_packaging_cost",
    "min_price",
    "min_acceptable_price",
    "fast_sale_price",
    "patient_price",
    "estimated_value",
    "target_price",
    "location",
    "storage_location",
    "acquisition_source",
    "supplier",
    "notes",
    "confidence_reason",
    "confidence_score",
    "override_reason",
}
