# Generated by Django 5.2.15 on 2026-06-16 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoasset',
            name='fixup_status',
            field=models.CharField(choices=[('none', 'None'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='PhotoDerivative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_review', max_length=20)),
                ('source', models.CharField(choices=[('local_fixup', 'Local fix-up'), ('local_tweak', 'Local tweak')], default='local_fixup', max_length=20)),
                ('fixed_path', models.CharField(max_length=500)),
                ('thumb_path', models.CharField(blank=True, default='', max_length=500)),
                ('source_path', models.CharField(max_length=500)),
                ('original_processed_path', models.CharField(blank=True, default='', max_length=500)),
                ('original_thumb_path', models.CharField(blank=True, default='', max_length=500)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes_fixed', models.PositiveIntegerField(blank=True, null=True)),
                ('pipeline_version', models.CharField(default='sprint17-local-v1', max_length=40)),
                ('operations', models.JSONField(blank=True, default=list)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('background_mode', models.CharField(blank=True, default='', max_length=80)),
                ('condition_note', models.TextField(blank=True, default='')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivatives', to='photos.photoasset')),
            ],
            options={
                'ordering': ['photo', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='photoasset',
            name='active_derivative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photos.photoderivative'),
        ),
        migrations.AddIndex(
            model_name='photoderivative',
            index=models.Index(fields=['photo', 'status'], name='photo_derivative_status_idx'),
        ),
    ]
