# Generated by Django 5.2.15 on 2026-06-09 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_inventoryitem_est_outbound_shipping_and_more'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('final_value_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('per_order_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('promoted_pct', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('gst_pct', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('default_packaging_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('default_outbound_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ValuationComparable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('included', models.BooleanField(default=True)),
                ('exclude_reason', models.TextField(blank=True, default='')),
                ('comparable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='research.comparable')),
            ],
        ),
        migrations.CreateModel(
            name='ValuationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.CharField(choices=[('comp_based', 'Comparable-based'), ('commodity_manual', 'Commodity (manual inputs)'), ('commodity_live', 'Commodity (live spot) - Sprint 3')], default='comp_based', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('estimate_low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimate_median', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimate_high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fast_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('patient_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_acceptable_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('confidence_reason', models.TextField(blank=True, default='')),
                ('is_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('comparables', models.ManyToManyField(related_name='valuation_reports', through='valuation.ValuationComparable', to='research.comparable')),
                ('fee_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valuation_reports', to='valuation.feeschedule')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_reports', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='valuationcomparable',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_links', to='valuation.valuationreport'),
        ),
        migrations.AddConstraint(
            model_name='valuationreport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('item',), name='one_current_valuation_per_item'),
        ),
        migrations.AddConstraint(
            model_name='valuationreport',
            constraint=models.CheckConstraint(condition=models.Q(('is_overridden', False), models.Q(('override_reason', ''), _negated=True), _connector='OR'), name='valuation_override_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='valuationcomparable',
            constraint=models.UniqueConstraint(fields=('report', 'comparable'), name='uniq_report_comparable'),
        ),
        migrations.AddConstraint(
            model_name='valuationcomparable',
            constraint=models.CheckConstraint(condition=models.Q(('included', True), models.Q(('exclude_reason', ''), _negated=True), _connector='OR'), name='excluded_comparable_has_reason'),
        ),
    ]
