# Generated by Django 5.2.15 on 2026-06-10 03:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalSpotCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metal', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('palladium', 'Palladium')], max_length=12)),
                ('currency', models.CharField(default='AUD', max_length=3)),
                ('provider', models.CharField(max_length=60)),
                ('price_per_gram', models.DecimalField(decimal_places=6, max_digits=14)),
                ('provider_price', models.DecimalField(decimal_places=6, max_digits=14)),
                ('provider_units', models.CharField(max_length=20)),
                ('as_of', models.DateTimeField()),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['metal', 'currency', 'provider'],
                'constraints': [models.UniqueConstraint(fields=('metal', 'currency', 'provider'), name='uniq_metal_currency_provider')],
            },
        ),
    ]
