# Generated by Django 5.2.15 on 2026-06-14 02:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_inventoryitem_quantity_total_and_more'),
        ('listing', '0002_alter_listingdraft_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('channel', models.CharField(choices=[('ebay_au', 'eBay AU'), ('manual', 'Manual'), ('other', 'Other')], default='manual', max_length=20)),
                ('actual_fees_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_fee_breakdown', models.JSONField(blank=True, default=dict)),
                ('actual_shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost_basis_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valuation_snapshot', models.JSONField(blank=True, default=dict)),
                ('estimated_fee_snapshot', models.JSONField(blank=True, default=dict)),
                ('provenance', models.CharField(choices=[('manual', 'Manual'), ('ebay_sync', 'eBay sync')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('corrected_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='sales.salerecord')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.inventoryitem')),
                ('listing_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='listing.listingdraft')),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
                'indexes': [models.Index(fields=['item', 'sale_date'], name='sales_saler_item_id_cf5b1c_idx'), models.Index(fields=['channel'], name='sales_saler_channel_c43466_idx'), models.Index(fields=['provenance'], name='sales_saler_provena_694a0a_idx'), models.Index(fields=['corrected_from'], name='sales_saler_correct_73a50f_idx')],
            },
        ),
    ]
