# Generated by Django 5.2.15 on 2026-06-14 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_quantity_total_and_more'),
        ('listing', '0002_alter_listingdraft_status'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='channel_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='cost_basis_unknown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='ebay_line_item_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='ebay_order_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='ebay_transaction_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='fee_status',
            field=models.CharField(choices=[('authoritative', 'Authoritative'), ('estimated_or_unmapped', 'Estimated or unmapped')], default='authoritative', max_length=32),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='inventory.inventoryitem'),
        ),
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['ebay_order_id', 'ebay_line_item_id'], name='sales_saler_ebay_or_b5d0c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='salerecord',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('ebay_order_id', ''), _negated=True), models.Q(('ebay_line_item_id', ''), _negated=True), ('corrected_from__isnull', True)), fields=('ebay_order_id', 'ebay_line_item_id'), name='uniq_active_ebay_order_line_sale'),
        ),
    ]
